@host=http://localhost:4500



### Page d'accueil avec les 3 infos qui m'interessent
GET {{host}}

### Toutes les langues
GET {{host}}/languages

### Un language particulier
GET {{host}}/languages/2

###ajouter une langue
POST {{host}}/languages/save
Content-Type: application/json

{
    "name": "Français"
    }

###Supprimer une langue
DELETE {{host}}/languages/17
